<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.seckill</groupId>
        <artifactId>SK-user</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>user-api</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>
    <name>user-api</name>
    <properties>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <revision>release-1.0.0</revision>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.seckill</groupId>
            <artifactId>user-constant</artifactId>
        </dependency>
        <dependency>
            <groupId>com.seckill</groupId>
            <artifactId>user-ao</artifactId>
        </dependency>
        <dependency>
            <groupId>com.seckill</groupId>
            <artifactId>user-bo</artifactId>
        </dependency>
        <dependency>
            <groupId>com.seckill</groupId>
            <artifactId>user-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>com.seckill</groupId>
            <artifactId>SK-common</artifactId>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
        </dependency>
    </dependencies>


</project>